trying to set the C# language version to the latest to avoid errors: "error CS8124: Tuple must contain at least two elements", "Feature 'using declarations' is not available in C# 7.3. Please use language version 8.0 or greater", and "A new expression requires (), [], or {} after type"